data_path: "../data_release/"
res_path: "release_ensemble_preds/train/WCG/" # path to raw predictions, see README for more details
out_path: "release_ensemble_tensor_data/"
restrict: null # can be used to only select a subset of datasets
ignore_ds: [big] #THis is used to only consider equal sizes predictions
naming: "small"

no_instant_preds: ["direct_crosscorr","var", "pcmci","cp"]