p: "" #path where previous results all previous products are stoed.
model_p:  "best_ensembles/"
val_ds_path: "release_ensemble_tensor_data/test_corrected/small/" #data path for the labels
method_selection: "SimpleLinear"
out_folder: "release_ensemble_performance"
restrict_violations: null
modus: "inst_inst"

normalize_input: True

predict: True
size_selection: 5  # choose number of vars in the dataset (5 = small, 7=big)

rivers_predict: False
rivers_path: "processed_predictions.p"

cache: True
cache_path: "release_ensemble_cache/"