defaults:
  - _self_

paths:
  result_p: "ensemble_experiments/release_ensemble_tensor_data/test_corrected/"
  output_dir: "ensemble_experiments/release_ensemble_summarized_results/ensemble_predictions/"
  model_p: "ensemble_experiments/reproduce_performance/"

experiment:
  expected_samples: 100
  verbose: 0

restrict_to: 3
modus: mean_predictions


model: SimpleLinear
size: small

performance_score: "SHD individual"

normalize_predictions: True 

