
defaults:
  - _self_
  #- override hydra/hydra_logging: disabled
  #- override hydra/job_logging: disabled
  - base_model: convM.yaml
  - override hydra/launcher: submitit_slurm
 


directory: "/home/datasets4/stein/robust_exp/ensemble_experiment/deep_runs/${now:%Y-%m-%d_%H-%M-%S-%f}/"
logging_interval:



trainer:
  _target_: lightning.pytorch.trainer.Trainer
  #default_root_dir: ${paths.checkpoint_dir} # can be done with more stuff
  max_epochs: 500
  accelerator: "auto" #auto
  devices: auto
  precision: "16-mixed" # mixed precision for extra speed-up
  check_val_every_n_epoch: 1
  deterministic: True
  enable_checkpointing: True # TODO enable in the actual experiment then!
  #overfit_batches: 1
  log_every_n_steps: 99999999999999999999



extras:
  ignore_warnings: False
  pretty_errors: True


tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: ${directory}
  name: "null"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  version: null

seed: 42


model:
  _target_: dl_components.pl_wrappers.Architecture_PL

  base_model: ${base_model}
  
  loss_type: "mse"
  val_metric_name: "AUROC"
  optimizer_lr: 1e-2
  weight_decay: 0.01

data:
  _target_: dl_components.pl_wrappers.GeneratorDataModule
  train_ds_path: "/home/datasets4/stein/robust_exp/ensemble_experiment/trainbig_.p"
  val_ds_path: "/home/datasets4/stein/robust_exp/ensemble_experiment/testbig_.p" # TODO Add a new set for HP fitting later.
  test_ds_path: "/home/datasets4/stein/robust_exp/ensemble_experiment/testbig_.p"
  batch_size: 32
  restrict_samples_for_debugging: null


early_stopping: 
  _target_: lightning.pytorch.callbacks.EarlyStopping
  patience: 10   # I guess that is already quite a bit?
  min_delta: 0
  mode: max



hydra:
  launcher: 
    cpus_per_task: 4
    #gpus_per_task: 1
    mem_gb: 8
    timeout_min: 480
    gres: shard:4
    partition: robolab
    #partition: workstation,robolab 